ecommerce:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5433
      user: admin
      password: changeme
      dbname: ecommerce
      schema: public
      threads: 4
